server:
  port: "$PORT:8080"

digdir:
  baseUrl: "$?DIGDIR_BASE_URL"

externalFiltering:
  enabled: "$?EXTERNAL_FILTERING_ENABLED"
  url: "$?EXTERNAL_FILTERING_URL"

accessLog:
  enabled: "$?ACCESS_LOG_ENABLED"

logback:
  configFile: "$?LOGBACK_CONFIG_FILE"
